### ISSUE TITLE
Useless User ID in requests

### ISSUE THREAD

**Issue by inviqus** [evo-doc/back-end#10]
Proc u pozadavku typu `/user/activation` se vyzaduje uvadeni uplne zbytecneho `user_id` spolu s tokenem? Pridava to praci pro kontrolu konzistence dat, kontrolu spravnosti id + token apod.

Staci prece posilat token a z toho se na serveru 100% presnosti vytahne ID necim typu:
```javascript
let id = +token.substr(0, 10);
```

Useless ID je v 
```
/user/activation
/user/authorised
DELETE /user
atd.
```

Navic je to zavadejici, protoze pozadavek 
`GET /user?token={token}&user_id={user_id}` uz oznacuje jako `user_id` ne aktualniho uzivatele, ale toho, jehoz data chceme ziskat.

**Comment by TomStary** [comment]
Okey, upravíme

**Comment by DanHampl** [comment]
neupravime co kdyz je admin a chce aktivovat jinyho uzivatele puvodni myslenka byla zkontrolovat jestli id a uzvatel tokenu sou stejny a pokud ne tak se podivat jestli to nahodou neni admin

**Comment by TomStary** [comment]
No to prej Sergej zatím neche, už sem to s ním řešil

**Comment by DanHampl** [comment]
sergej si to as otevre kdyz nahodou bude chtit zmenu
