### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TomStary** [evo-doc/back-end#18]

**Comment by DanHampl** [comment]
should be done please check and close

**Comment by TomStary** [comment]
# Aktuální stav - výpis chybějících
evodoc.entity.module
--------------------
Classes:
 * Module -- missing methods:

   - serialize

evodoc.entity.permission
------------------------
Classes:
 * ModulePerm -- missing methods:

   - serialize
 * ProjectPerm -- missing methods:

   - save_entity
   - serialize

evodoc.entity.project
---------------------
Classes:
 * Project -- missing methods:

   - serialize

evodoc.entity.user
------------------
Classes:
 * User -- missing methods:

   - serialize
 * UserToken -- missing methods:

   - serialize
 * UserType -- missing methods:

   - serialize

**Comment by TomStary** [comment]
Misclick
