### ISSUE TITLE
UserType in tests

### ISSUE THREAD

**Issue by TomStary** [evo-doc/back-end#23]
@DanHampl měli bychom nějak vyřešit ty UserType v testech, protože na tohle jsou tam seedy, jenom je problém, že UserType se na konci každého testu smaže, možná by to chtělo, UserType přestat mazat, a pouze ho resetovat do stavu, do kterého ho dostanou seedy, tedy, pokud tam jsou nějaké změny. Ten problém co byl včera v noci byl právě kvůli tomu, že jsme necheckovali při testech jestli se DB naplní testovacími daty.

**Comment by DanHampl** [comment]
tak muzu udelat este test ze seedy prosli ale kdyz testujem user type tak to stejne budem mazat a hlavne bysme museli prepsat pul testu ted a na to uplne neni cas ani energie
