### ISSUE TITLE
Aktivace uživatele

### ISSUE THREAD

**Issue by TomStary** [evo-doc/back-end#6]
Je možné aby jiný uživatel aktivoval uživatele (token nepatří aktivovanému uživateli)

**Comment by inviqus** [comment]
Tak kazdy uzivatel ma svuj vlastni token, pod kterym je lognuty. Pokud by poslal pozadavek na server, kde by nebyl jeho token, tak to mas rovnou zahodit a vratit mi 403. Spolu s tokenem ti budu posilat (prozatim random) validation code. 

Nechapu, jak by mohla nastat situace, kdy jiny uzivatel by aktivoval jineho uzivatele, aniz by mel jeho token. 

A kdyz uz mam jeho token, tak z toho vyplyva, ze jsem tim druhym uzivatelem.
